# 基础镜像 不指定版本则默认最新
FROM nginx
# author
MAINTAINER sunny

# 挂载目录
VOLUME /home/nginx/www/dist/ruoyi-ui
# 创建目录
RUN mkdir -p /home/nginx/www/dist/ruoyi-ui
# 指定路径 该路径我是自己提前创建好的
WORKDIR /home/nginx/www/dist/ruoyi-ui
# 复制conf文件到路径 ./conf/nginx.conf和上面的mysql一个道理 nginx.conf下面会贴出来
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径 dist中存放前端项目的打包文件
COPY ./html/dist /home/nginx/www/dist/ruoyi-ui